#version: '3'
#
#services:
#  db:
#    image: postgres
#  web:
#    build: .
#    command: python mysite/manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

 version: '3'

 services:
   db:
     image: postgres
     ports:
       - "5432:5432"
   web:
     image: registration
     environment:
       - NODE_ENV=development
       - PYTHONUNBUFFERED=0
     build: .
     command: bash -c "python mysite/manage.py migrate; python mysite/manage.py runserver 0.0.0.0:8000"
     volumes:
       - .:/code
     ports:
       - "8000:8000"
       - "3000:3000"
     depends_on:
       - db
