version: '3'

services:
 db:
   image: postgres
   ports:
     - "5432:5432"
 web:
   image: registration
   environment:
     - SECRET_KEY # might need to add extra $ to escape $ (i.e. turn abc$abc to abc$$abc)
     - SOCIAL_AUTH_JHU_KEY
     - SOCIAL_AUTH_JHU_SECRET
     - DB_NAME
     - DB_USER
     - DB_PASS
     - NODE_ENV=development
     - PYTHONUNBUFFERED=0
   build: .
   # Just migrations for testing, you will need to commend out db code in forms.py
   #command: sh -c "python mysite/manage.py migrate;"
   command: sh -c "python mysite/manage.py migrate; python mysite/manage.py runserver 0.0.0.0:8000"
   volumes:
     - .:/code
   ports:
     - "8000:8000"
     - "3000:3000"
   depends_on:
     - db
