# Generated by Django 2.2.4 on 2019-08-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0014_auto_20190825_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
            ],
        ),
    ]
