FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY main.css /usr/share/nginx/html/main.css
COPY pilotLogo.png /usr/share/nginx/html/pilotLogo.png
COPY closed-icon.png /usr/share/nginx/html/closed-icon.png
COPY index.html /usr/share/nginx/html/index.html
